### ISSUE TITLE
Data are not always ready when asked

### ISSUE THREAD

**Issue by robinalexandre** [meteocontrol/vcom-api-client#2]
Hello,

I got a cron tab to query the data from inverters with the bulk api endpoint every 15 minutes.

If I set for example the "to" parameter to 2022-03-15T13:15:00+01:00, most of the time I don't get the data corresponding to this exact end time. 
I think it depends on the time you need to get the data from the gateway.

Can you tell me how much time you need to get the datas from your side ?
It would help me knowing how much I should wait before querying the data.

Thank you,
Alexandre

**Comment by lordmonkey42** [comment]
Dear Alexandre

Thank you for the report and for using the client.

Regarding your question, there are truly some delays from data uploading and processing.

The onsite devices may have some delay due to network connection or their configurations, and the mc data center also needs some time to process the data. So if you may not get real-time data all the time.

We’d suggest you wait for about 5 minutes to get the latest data.

Sincerely

**Comment by robinalexandre** [comment]
Hello,

Thank you for your quick answer.

I will look into that then. 
I close the issue
